### ISSUE TITLE
KeyError: 'HGT'

### ISSUE THREAD

**Issue by AleksanderKamienski** [aamks/aamks#60]
Normal exit from CFAST
Traceback (most recent call last):
  File "/usr/local/aamks/evac/worker.py", line 486, in <module>
    w.local_worker()
  File "/usr/local/aamks/evac/worker.py", line 475, in local_worker
    self.do_simulation()
  File "/usr/local/aamks/evac/worker.py", line 271, in do_simulation
    i.do_simulation(step)
  File "/usr/local/aamks/evac/rvo2_dto.py", line 338, in do_simulation
    self.set_goal()
  File "/usr/local/aamks/evac/rvo2_dto.py", line 178, in set_goal
    goal = self.nav.nav_query(src=position, dst=self._find_closest_exit(e), maxStraightPath=32)
  File "/usr/local/aamks/evac/rvo2_dto.py", line 82, in _find_closest_exit
    if self._next_room_in_smoke(evacuee, path) is not True:
  File "/usr/local/aamks/evac/rvo2_dto.py", line 112, in _next_room_in_smoke
    od_next_room = self.smoke_query.get_visibility(path[1])
  File "/usr/local/aamks/fire/partition_query.py", line 264, in get_visibility
    hgt = conditions['HGT']
KeyError: 'HGT'

**Comment by kowalskiw** [comment]
Resolved with pull request #64
